#!/usr/bin/env python3
"""Run all built kernel benchmarks and emit JSON for the website charts.

Parses the harness output ("<name>  <ms> ms | <gb> GB/s (...) | <gflops> GFLOP/s
(...)") from each executable under kernels/build and writes a JSON document in
the shape expected by website/content/data/benchmarks.json.

Usage:
    python scripts/bench_all.py --build-dir kernels/build \
        --out website/content/data/benchmarks.json

If no build directory exists, run cmake first:
    cmake -B kernels/build -S kernels && cmake --build kernels/build -j
"""

import argparse
import json
import os
import re
import subprocess
import sys

_LINE_RE = re.compile(
    r"^(?P<name>\S+)\s+(?P<ms>[\d.]+)\s+ms\s+\|\s+(?P<gb>[\d.]+)\s+GB/s.*?\|\s+(?P<gflops>[\d.]+)\s+GFLOP/s"
)

_GEMM_STEPS = [
    "sgemm_step0_naive",
    "sgemm_step1_shared",
    "sgemm_step2_register_tiling",
    "sgemm_step3_vectorized",
    "sgemm_step4_double_buffer",
]


def run_executable(path: str) -> dict:
    """Run one benchmark binary and return {name: {ms, gb, gflops}}."""
    results = {}
    try:
        proc = subprocess.run([path], capture_output=True, text=True, timeout=600, check=False)
    except (OSError, subprocess.TimeoutExpired) as exc:
        print(f"  skip {path}: {exc}", file=sys.stderr)
        return results
    for line in proc.stdout.splitlines():
        m = _LINE_RE.match(line.strip())
        if m:
            results[m.group("name")] = {
                "ms": float(m.group("ms")),
                "gb": float(m.group("gb")),
                "gflops": float(m.group("gflops")),
            }
    return results


def collect(build_dir: str) -> dict:
    all_results = {}
    for root, _dirs, files in os.walk(build_dir):
        for fname in files:
            path = os.path.join(root, fname)
            if os.access(path, os.X_OK) and not fname.endswith((".o", ".cmake", ".txt")):
                if os.path.isfile(path):
                    all_results.update(run_executable(path))
    return all_results


def build_gemm_series(results: dict, platform: str, device: str, reference: str) -> dict:
    steps = []
    ref_gflops = None
    for name in _GEMM_STEPS:
        if name in results:
            steps.append({"name": name, "gflops": round(results[name]["gflops"], 1)})
    if steps:
        ref_gflops = max(s["gflops"] for s in steps)
        for s in steps:
            s["pctOfRef"] = round(100.0 * s["gflops"] / ref_gflops, 1) if ref_gflops else 0.0
    return {
        "device": device,
        "reference": reference,
        "peakTflops": 0.0,
        "steps": steps,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build-dir", default="kernels/build")
    parser.add_argument("--out", default="website/content/data/benchmarks.local.json")
    parser.add_argument("--platform", default="cuda", choices=["cuda", "rocm"])
    parser.add_argument("--device", default="my device")
    parser.add_argument("--reference", default="library")
    args = parser.parse_args()

    if not os.path.isdir(args.build_dir):
        print(f"Build dir {args.build_dir} not found. Run cmake first.", file=sys.stderr)
        sys.exit(1)

    print(f"Running benchmarks under {args.build_dir} ...")
    results = collect(args.build_dir)
    print(f"Collected {len(results)} kernel results.")

    document = {
        "_note": "Generated by scripts/bench_all.py on real hardware.",
        "raw": results,
        "gemm": {
            args.platform: build_gemm_series(results, args.platform, args.device, args.reference),
        },
    }

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(document, fh, indent=2, ensure_ascii=False)
    print(f"Wrote {args.out}. Merge into website/content/data/benchmarks.json to update charts.")


if __name__ == "__main__":
    main()
